export default {
    dark: false,
    colors: {
        background: "#F5F5F5",
        surface: "#FFFFFF",
        "surface-bright": "#FFFFFF",
        "surface-light": "#D4E8DC",
        "surface-variant": "#B2DFDB",
        "on-surface-variant": "#212121",
        primary: "#128C7E",
        "primary-darken-1": "#075E54",
        secondary: "#25D366",
        "secondary-darken-1": "#1DB954",
        error: "#D32F2F",
        info: "#03A9F4",
        success: "#4CAF50",
        warning: "#FFC107",
    },
    variables: {
        "border-color": "#B2DFDB",
        "border-opacity": 0.12,
        "high-emphasis-opacity": 0.87,
        "medium-emphasis-opacity": 0.6,
        "disabled-opacity": 0.38,
        "idle-opacity": 0.04,
        "hover-opacity": 0.08,
        "focus-opacity": 0.12,
        "selected-opacity": 0.1,
        "activated-opacity": 0.14,
        "pressed-opacity": 0.1,
        "dragged-opacity": 0.08,
        "theme-kbd": "#FFFFFF",
        "theme-on-kbd": "#128C7E",
        "theme-code": "#F1F8E9",
        "theme-on-code": "#000000",
    },
};
